// Mock seed data for the philía wireframe demo.
// Includes vibe vectors, locations, and history so the matching
// engine has real numbers to chew on.

const CT = [42.4426, -76.4855]; // Collegetown anchor
const NC = [42.4554, -76.4775]; // North Campus
const COMMONS = [42.4396, -76.4969];

export const seedUsers = [
  {
    id: "u_maya",
    name: "Maya K.",
    emoji: "🌶",
    year: "Junior",
    major: "ILR",
    pronouns: "she/her",
    age: 21,
    bio: "craving spice + soup. studying law-econ. I will absolutely talk your ear off about live music.",
    vibe: { ramen: 1, indian: 0.9, korean: 0.7, boba: 0.8, coffee: 0.7, chill: 1, "post-class": 1, loud: 0.4, quiet: 0.3, "study-after": 0.9, "first-dates ok": 0.6 },
    cuisinePref: ["ramen", "indian", "korean", "vietnamese"],
    food: ["ramen", "indian", "korean", "boba", "vegetarian-ok", "no oysters"],
    budget: 2,
    groupSizePref: [2, 3, 4],
    timeWindowPref: [17, 22],
    loc: [42.4438, -76.4869],
    history: { attended: 22, cancelled: 1, flakes: 0 },
    connections: ["u_sam", "u_jules", "u_priya", "u_nico", "u_wen"],
  },
  {
    id: "u_nico",
    name: "Nico",
    emoji: "🌿",
    year: "Junior",
    major: "CS",
    vibe: { indian: 1, ramen: 0.6, chill: 1, "post-class": 0.8, quiet: 0.6, "study-after": 0.7, vegetarian: 1 },
    cuisinePref: ["indian", "thai", "ramen"],
    budget: 2,
    groupSizePref: [3, 4],
    timeWindowPref: [18, 21],
    loc: CT,
    history: { attended: 31, cancelled: 0, flakes: 0 },
    connections: ["u_maya", "u_avi", "u_priya"],
  },
  {
    id: "u_avi",
    name: "Avi",
    emoji: "🎧",
    year: "Sophomore",
    major: "ILR",
    vibe: { kbbq: 1, ramen: 0.6, loud: 0.9, "post-class": 0.7, "first-dates ok": 0.5, indian: 0.4 },
    cuisinePref: ["kbbq", "ramen", "indian"],
    budget: 3,
    groupSizePref: [3, 4, 5],
    timeWindowPref: [18, 23],
    loc: CT,
    history: { attended: 18, cancelled: 1, flakes: 1 },
    connections: ["u_nico", "u_maya"],
  },
  {
    id: "u_priya",
    name: "Priya",
    emoji: "🍓",
    year: "Junior",
    major: "Bio",
    vibe: { indian: 0.9, ramen: 0.7, vegetarian: 1, chill: 1, quiet: 0.7, "study-after": 0.8 },
    cuisinePref: ["indian", "ramen", "thai"],
    budget: 2,
    groupSizePref: [2, 3],
    timeWindowPref: [17, 21],
    loc: NC,
    history: { attended: 12, cancelled: 1, flakes: 0 },
    connections: ["u_maya", "u_nico"],
  },
  {
    id: "u_sam",
    name: "Sam",
    emoji: "🐝",
    year: "Senior",
    major: "Eng",
    vibe: { ramen: 0.8, vietnamese: 0.9, chill: 0.8, loud: 0.5, "late night": 0.7 },
    cuisinePref: ["vietnamese", "ramen"],
    budget: 1,
    groupSizePref: [2, 3],
    timeWindowPref: [19, 23],
    loc: COMMONS,
    history: { attended: 9, cancelled: 0, flakes: 1 },
    connections: ["u_maya", "u_jules"],
  },
  {
    id: "u_jules",
    name: "Jules",
    emoji: "🌊",
    year: "Junior",
    major: "Math",
    vibe: { bagels: 1, coffee: 1, quiet: 1, "study-after": 1, "post-class": 1 },
    cuisinePref: ["bagels", "coffee"],
    budget: 1,
    groupSizePref: [2, 3, 4],
    timeWindowPref: [19, 23],
    loc: CT,
    history: { attended: 14, cancelled: 0, flakes: 0 },
    connections: ["u_maya", "u_sam"],
  },
  {
    id: "u_wen",
    name: "Wen",
    emoji: "🦊",
    year: "Sophomore",
    major: "Hotel",
    vibe: { vietnamese: 1, ramen: 0.5, "cheap eats": 1, chill: 0.7, "first-dates ok": 0.7 },
    cuisinePref: ["vietnamese", "ramen"],
    budget: 1,
    groupSizePref: [3, 4],
    timeWindowPref: [18, 22],
    loc: COMMONS,
    history: { attended: 7, cancelled: 0, flakes: 0 },
    connections: ["u_maya"],
  },
  {
    id: "u_lin",
    name: "Lin",
    emoji: "🍜",
    year: "Senior",
    major: "AEM",
    vibe: { vietnamese: 1, ramen: 0.8, "cheap eats": 0.8, chill: 0.6, loud: 0.6 },
    cuisinePref: ["vietnamese", "ramen"],
    budget: 2,
    groupSizePref: [3, 4],
    timeWindowPref: [18, 22],
    loc: COMMONS,
    history: { attended: 6, cancelled: 1, flakes: 0 },
    connections: [],
  },
  {
    id: "u_reni",
    name: "Reni",
    emoji: "📚",
    year: "Sophomore",
    major: "Gov",
    vibe: { bagels: 1, coffee: 0.8, quiet: 1, "study-after": 1, "cheap eats": 0.9 },
    cuisinePref: ["bagels"],
    budget: 1,
    groupSizePref: [2, 3, 4],
    timeWindowPref: [20, 23],
    loc: CT,
    history: { attended: 4, cancelled: 0, flakes: 0 },
    connections: [],
  },
];

const T = (h, m = 0) => {
  const d = new Date();
  d.setHours(h, m, 0, 0);
  return d;
};

export const seedPlans = [
  {
    id: "p1",
    hostId: "u_nico",
    spot: "Mehak Indian Cuisine",
    cuisine: "indian",
    emoji: "🌿",
    startsAt: T(19, 0),
    distanceLabel: "in 48m · 4 min walk",
    location: "College Town",
    loc: CT,
    vibeTags: ["indian", "chill", "post-class"],
    budgetTier: 2,
    budgetPerPerson: 22,
    seats: 4,
    filledIds: ["u_nico", "u_avi", "u_priya"],
    waitlist: [],
    status: "open",
    createdAt: new Date(Date.now() - 90 * 60e3),
    note: "craving a hot soup after the prelim 😮‍💨",
  },
  {
    id: "p2",
    hostId: "u_avi",
    spot: "Koko Korean BBQ",
    cuisine: "kbbq",
    emoji: "🎧",
    startsAt: T(20, 0),
    distanceLabel: "in 1h 18m · College Town",
    location: "College Town",
    loc: CT,
    vibeTags: ["kbbq", "loud", "first-dates ok"],
    budgetTier: 3,
    budgetPerPerson: 38,
    seats: 4,
    filledIds: ["u_avi", "u_sam"],
    waitlist: [],
    status: "open",
    createdAt: new Date(Date.now() - 30 * 60e3),
  },
  {
    id: "p3",
    hostId: "u_reni",
    spot: "Collegetown Bagels",
    cuisine: "bagels",
    emoji: "📚",
    startsAt: T(21, 30),
    distanceLabel: "late · 2 min walk",
    location: "Collegetown",
    loc: CT,
    vibeTags: ["cheap eats", "study-after", "quiet"],
    budgetTier: 1,
    budgetPerPerson: 9,
    seats: 4,
    filledIds: ["u_reni"],
    waitlist: [],
    status: "open",
    createdAt: new Date(Date.now() - 10 * 60e3),
  },
  {
    id: "p4",
    hostId: "u_lin",
    spot: "Saigon Kitchen",
    cuisine: "vietnamese",
    emoji: "🍜",
    startsAt: T(20, 30),
    distanceLabel: "5 min walk",
    location: "Collegetown",
    loc: COMMONS,
    vibeTags: ["vietnamese", "cheap eats"],
    budgetTier: 2,
    budgetPerPerson: 16,
    seats: 4,
    filledIds: ["u_lin", "u_wen"],
    waitlist: [],
    status: "open",
    createdAt: new Date(Date.now() - 50 * 60e3),
  },
  {
    id: "p5",
    hostId: "u_jules",
    spot: "Gimme! Coffee",
    cuisine: "coffee",
    emoji: "☕",
    startsAt: T(18, 0),
    distanceLabel: "3 min walk",
    location: "Collegetown",
    loc: CT,
    vibeTags: ["coffee", "quiet", "study-after"],
    budgetTier: 1,
    budgetPerPerson: 7,
    seats: 3,
    filledIds: ["u_jules"],
    waitlist: [],
    status: "open",
    createdAt: new Date(Date.now() - 5 * 60e3),
  },
  {
    id: "p6",
    hostId: "u_priya",
    spot: "Thai Cuisine",
    cuisine: "thai",
    emoji: "🌶",
    startsAt: T(19, 30),
    distanceLabel: "in 1h · 6 min walk",
    location: "Collegetown",
    loc: CT,
    vibeTags: ["thai", "vegetarian", "chill"],
    budgetTier: 2,
    budgetPerPerson: 19,
    seats: 4,
    filledIds: ["u_priya", "u_nico"],
    waitlist: [],
    status: "open",
    createdAt: new Date(Date.now() - 25 * 60e3),
  },
  {
    id: "p7",
    hostId: "u_sam",
    spot: "Pho Time",
    cuisine: "vietnamese",
    emoji: "🍲",
    startsAt: T(21, 15),
    distanceLabel: "late · 4 min walk",
    location: "Commons",
    loc: COMMONS,
    vibeTags: ["vietnamese", "late night", "cheap eats"],
    budgetTier: 1,
    budgetPerPerson: 12,
    seats: 4,
    filledIds: ["u_sam"],
    waitlist: [],
    status: "open",
    createdAt: new Date(Date.now() - 15 * 60e3),
  },
  {
    id: "p8",
    hostId: "u_wen",
    spot: "Aladdin's Natural Eatery",
    cuisine: "mediterranean",
    emoji: "🥙",
    startsAt: T(18, 30),
    distanceLabel: "in 30m · 5 min walk",
    location: "Collegetown",
    loc: CT,
    vibeTags: ["mediterranean", "vegetarian", "first-dates ok"],
    budgetTier: 2,
    budgetPerPerson: 17,
    seats: 4,
    filledIds: ["u_wen", "u_jules"],
    waitlist: [],
    status: "open",
    createdAt: new Date(Date.now() - 40 * 60e3),
  },
  {
    id: "p9",
    hostId: "u_avi",
    spot: "Ithaca Ramen",
    cuisine: "ramen",
    emoji: "🍜",
    startsAt: T(19, 45),
    distanceLabel: "in 1h 15m · 7 min walk",
    location: "Commons",
    loc: COMMONS,
    vibeTags: ["ramen", "loud", "post-class"],
    budgetTier: 2,
    budgetPerPerson: 18,
    seats: 5,
    filledIds: ["u_avi", "u_sam", "u_lin"],
    waitlist: [],
    status: "open",
    createdAt: new Date(Date.now() - 35 * 60e3),
  },
  {
    id: "p10",
    hostId: "u_reni",
    spot: "Stella's Late Night",
    cuisine: "diner",
    emoji: "🌙",
    startsAt: T(22, 30),
    distanceLabel: "late · 5 min walk",
    location: "Collegetown",
    loc: CT,
    vibeTags: ["late night", "loud", "cheap eats"],
    budgetTier: 1,
    budgetPerPerson: 10,
    seats: 6,
    filledIds: ["u_reni", "u_avi"],
    waitlist: [],
    status: "open",
    createdAt: new Date(Date.now() - 8 * 60e3),
  },
];

export function seedFriendsOf(meId) {
  const me = seedUsers.find((u) => u.id === meId);
  return me ? me.connections : [];
}

export const seedBotThread = [
  {
    kind: "bot",
    text: "Plan locked. 4/4 confirmed for Mehak's, 7:00 pm. I'll nudge again at 6:30.",
  },
  { kind: "tag", text: "— 6:30 pm —" },
  {
    kind: "bot",
    text: "Vibe check 🫶 — react below.",
    actions: ["🟢 still in", "🟡 running 5", "🔴 can't make it"],
  },
  { kind: "me", text: "🟢 still in" },
  { kind: "bot-mini", text: "3 / 4 in. Waiting on Avi…" },
  {
    kind: "bot",
    text: "Avi's running 5. Pushing meetup to 7:05. Cool with everyone? 👍 / 👎",
  },
  {
    kind: "tip",
    text: "Pro tip: bot keeps numbers private. Want to share yours after? Say “swap contacts”.",
  },
];

/* ---------- legacy exports kept so existing imports don't break ---------- */
export const me = (() => {
  const u = seedUsers[0];
  return {
    name: u.name,
    emoji: u.emoji,
    year: u.year,
    major: u.major,
    pronouns: u.pronouns,
    age: u.age,
    reliability: 96,
    attended: u.history.attended,
    flakes: u.history.flakes,
    cancelled: u.history.cancelled,
    connections: u.connections.length + 12,
    bio: u.bio,
    food: u.food,
    vibe: ["chill", "post-class", "study-after", "first-dates ok"],
    budget: "$$",
    groupSize: "2–4",
  };
})();

export const friends = seedFriendsOf("u_maya")
  .map((id) => seedUsers.find((u) => u.id === id))
  .filter(Boolean)
  .map((u) => ({ name: u.name, emoji: u.emoji }));

export const plans = seedPlans.map((p) => ({
  id: p.id,
  spot: p.spot,
  cuisine: p.cuisine,
  emoji: p.emoji,
  time: p.startsAt.toLocaleTimeString([], { hour: "numeric", minute: "2-digit" }).toLowerCase(),
  distanceLabel: p.distanceLabel,
  location: p.location,
  tags: p.vibeTags.slice(0, 3),
  host: (() => {
    const h = seedUsers.find((u) => u.id === p.hostId);
    return { name: h.name, emoji: h.emoji, reliability: 96 };
  })(),
  filled: p.filledIds.length,
  seats: p.seats,
  match: 0,
  more: Math.max(0, p.seats - p.filledIds.length - 1),
}));

export const featuredPlan = (() => {
  const p = seedPlans[0];
  const roster = p.filledIds.map((id) => {
    const u = seedUsers.find((x) => x.id === id);
    return {
      emoji: u.emoji,
      name: u.name,
      role: id === p.hostId ? "host" : "",
      sub: `${u.year} · ${u.major}`,
      tag: id === p.hostId ? "" : "1 mutual",
    };
  });
  while (roster.length < p.seats) {
    roster.push({ emoji: "?", name: "open", sub: "1 spot left — could be you", open: true });
  }
  return {
    id: p.id,
    spot: p.spot,
    time: p.startsAt.toLocaleTimeString([], { hour: "numeric", minute: "2-digit" }).toLowerCase(),
    in: "in 1h 18m",
    walk: "4 min walk",
    tags: p.vibeTags,
    match: 98,
    budgetPerPerson: p.budgetPerPerson,
    group: { filled: p.filledIds.length, seats: p.seats },
    roster,
    summary: "Solid match — recomputed live by the engine.",
  };
})();

export const botThread = seedBotThread;
export const nearbyTags = ["🍜", "🎧", "🌿", "📚", "☕", "+ 9 more"];
